### ISSUE TITLE
PyPI page still shows readme of old version

### ISSUE THREAD

**Issue by wesinator** [yamatt/homoglyphs#1]
Hi @yamatt , 

Happy new year! 
Thanks for maintaining this fork.

However it seems the PyPI page on https://pypi.org/project/homoglyphs_fork/ still shows the readme of the old original version as the project description, not loading your README.md contents specified by the pyproject.toml 

Not sure quite what's causing that, but maybe the [setup.py](https://github.com/yamatt/homoglyphs/blob/8d3e36acf1f9a00977f22080f2e7e7ab0fb176a2/setup.py#L16) needs to be updated ?
I'm not familiar with pyproject.toml specification yet - it seems something is causing PyPI to load the description from the readme of the original version, even though the other pieces are correct.

**p.s.** do you think it would make sense to make this project an org, move it to homoglyphs/homoglyphs ? 
That way there could be several maintainers added to the project.

There is also a forker at https://github.com/AnatolyTimakov/homoglyphs/commit/a70aa9ff975d149ec992815431cf4518ba6dfdd0 that added some content.

Thanks,

**Comment by yamatt** [comment]
Hi @wesinator thanks for telling me.

I think PyPI didn't get updated as I had done things out of sequence and I updated the README after the GitHub Action had been run. I'll see if I can trigger a manual update but I remember it being a faff involving versioning which is why I didn't bother.

I would expect it to be updated once a new version of this fork gets published.

As for the Organisation I'm not sure owning the entire Homoglyphs group is entirely useful. I'm happy to add people to this repo as is warranted for now in the same one way the original project was run.

I'll definitely check out the other fork.

**Comment by yamatt** [comment]
The description on PyPI is now updated because of the v2.1.0 release
